// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpM5OGT__jp_8GJ0xjOpSxgWc71lFRYmU',
    appId: '1:277495834817:web:185cce0363c2910e6e4c40',
    messagingSenderId: '277495834817',
    projectId: 'testing123-71872',
    authDomain: 'testing123-71872.firebaseapp.com',
    databaseURL: 'https://testing123-71872-default-rtdb.firebaseio.com',
    storageBucket: 'testing123-71872.appspot.com',
    measurementId: 'G-MK3R390KQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIXnsc3qhgfK2cI1tgEc8bUWhomAntK8U',
    appId: '1:277495834817:android:6e30dd1aedb274b36e4c40',
    messagingSenderId: '277495834817',
    projectId: 'testing123-71872',
    databaseURL: 'https://testing123-71872-default-rtdb.firebaseio.com',
    storageBucket: 'testing123-71872.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwr-SppITF_s0Y0tIdaymd5SJJI4179fE',
    appId: '1:277495834817:ios:6939813062cccf676e4c40',
    messagingSenderId: '277495834817',
    projectId: 'testing123-71872',
    databaseURL: 'https://testing123-71872-default-rtdb.firebaseio.com',
    storageBucket: 'testing123-71872.appspot.com',
    iosBundleId: 'com.virtual.virtualclassroomhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwr-SppITF_s0Y0tIdaymd5SJJI4179fE',
    appId: '1:277495834817:ios:6939813062cccf676e4c40',
    messagingSenderId: '277495834817',
    projectId: 'testing123-71872',
    databaseURL: 'https://testing123-71872-default-rtdb.firebaseio.com',
    storageBucket: 'testing123-71872.appspot.com',
    iosBundleId: 'com.virtual.virtualclassroomhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpM5OGT__jp_8GJ0xjOpSxgWc71lFRYmU',
    appId: '1:277495834817:web:f2f874469b1db2e16e4c40',
    messagingSenderId: '277495834817',
    projectId: 'testing123-71872',
    authDomain: 'testing123-71872.firebaseapp.com',
    databaseURL: 'https://testing123-71872-default-rtdb.firebaseio.com',
    storageBucket: 'testing123-71872.appspot.com',
    measurementId: 'G-H1WL8MR0DB',
  );
}
